version: 0.2

env:
  variables:
    S3_BUCKET: "halloween-personality-test-frontend-bucket-zzawook"

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - echo "Node version $(node --version)"
      - echo "NPM version $(npm --version)"
      - ls -la
      - pwd
      - whoami
      - cd frontend && npm ci
      
  build:
    commands:
      - echo "Building React application..."
      - pwd
      - npm run build
      - echo "Build completed successfully"
      - echo "Build output directory contents:"
      - ls -lah dist/
      
  post_build:
    commands:
      - pwd
      - echo "Uploading build files to S3..."
      - echo "Target - s3://$S3_BUCKET/"
      
      # Upload all files except index.html with long cache
      - aws s3 sync ./dist s3://$S3_BUCKET/ 
          --delete 
          --exclude "index.html" 
          --cache-control "public, max-age=31536000, immutable"
      
      # Upload index.html with no cache (for SPA routing)
      - aws s3 cp ./dist/index.html s3://$S3_BUCKET/index.html 
          --cache-control "no-cache, no-store, must-revalidate"
      
      - echo "Files uploaded successfully"
      - echo "S3 Website URL - http://$S3_BUCKET.s3-website-us-east-1.amazonaws.com"
      
      - echo "Deployment completed successfully!"
